# Site settings
title: CSS-Tricks 中文版
email: lixinyang1026@gmail.com
description: CSS-Tricks Blog Posts Simplified Chinese Translation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://li-xinyang.com/CSSTricks" # the base hostname & protocol for your site
github_username:  li-xinyang


# Build settings
markdown: kramdown
